# =======================
#### BASIC CONFIGURATION
# =======================

title: Christian Orlando
email: cnorlando@gmail.com
description: Multimedia Actor
url: "http://christianorlando.com"
baseurl: /cno
markdown: kramdown

instagram-username: christianorlando
tumblr-username: cnorlando
twitter-username: mobilebugle
