# =======================
#### BASIC CONFIGURATION
# =======================

title: Christian Orlando
email: cnorlando@gmail.com
description: Multimedia Actor
url: "http://christianorlando.com"
# baseurl: /cno
markdown: kramdown
permalink: none

instagram-username: christianorlando
tumblr-username: cnorlando
twitter-username: mobilebugle

github-url: carolineorlando.github.io
github-repo-url: carolineorlando.github.io/cno
