# =======================
#### BASIC CONFIGURATION
# =======================

title: Christian Orlando
email: cnorlando@gmail.com
description: Multimedia Artist
url: "http://christianorlando.com"
# baseurl: /cno
markdown: kramdown
permalink: none

instagram-username: christianorlando
tumblr-username: cnorlando
twitter-username: mobilebugle
vimeo-username: user19767938

sass:
  style: compressed
